{
  log.error("Test: '{}'",1);
  try {
    throw new IllegalArgumentException("meine Exception");
  }
 catch (  Exception ex) {
    log.error("Test: '{}'",1,ex);
  }
  try {
    Args.isTrue(false,"args error: %s",123);
  }
 catch (  Exception ex) {
    log.error("Test: '{}'",321,ex);
  }
}
