{
  try {
    close(closeable);
  }
 catch (  IOException e) {
    log.debug("closing resource failed: " + e.getMessage(),e);
  }
}
