{
  NullPointerException npe=new NullPointerException();
  Class c=Class.forName(getExceptionClassName());
  Constructor constructor=c.getConstructor(new Class[]{String.class,Throwable.class});
  Exception e=(Exception)constructor.newInstance("test message",npe);
  Assert.assertNotNull("Exception should be created",e);
  Assert.assertEquals("test message",e.getMessage());
  Assert.assertSame(npe,e.getCause());
}
