{
  Class c=Class.forName(getExceptionClassName());
  Constructor constructor=c.getConstructor(null);
  Exception e=(Exception)constructor.newInstance(null);
  Assert.assertNotNull("Exception should be created",e);
  Assert.assertNull(e.getMessage());
  Assert.assertNull(e.getCause());
}
